server:
  port: 5555
spring:
  application:
    name: gateway-server
  cloud:
    discovery:
      enabled: true;
    gateway:
      gdefault-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credetials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      metrics:
        enabled: true
      disovery:
        locator:
          enabled: true
          lower-case-servie-id: true
      routes:
        - id: delivery-ms
          uri: lb://delivery-ms
          predicates:
            - Path=/api/*/deliveries/**

        - id: order-ms
          uri: lb://order-ms
          predicates:
            - Path=/api/*/orders/**

        - id: product-ms
          uri: lb://product-ms
          predicates:
           - Path=/api/*/products/**

        - id: storage-ms
          uri: lb://storage-ms
          predicates:
           - Path=/api/*/storages/**

        - id: user-ms
          uri: lb://user-ms
          predicates:
           - Path=/api/*/auth/**

    loadbalaner:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}