server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TimurGinatulin/spring_config
          default-label: main
          username: TimurGinatulin
          password: 4119870Tim
          clone-on-start: true