server:
  port: 2021
  servlet:
    context-path: /api_v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_storage_db
    username: root
    password: root
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect