jwt:
  secret: apple
server:
  port: 0
  servlet:
   context-path: /api_v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_user_db
    username: root
    password: root
  application:
    name: user_ms
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}